name: Test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [14, 16, 18]

    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: yarn
      - name: Build
        run: yarn build
      - name: Unit Test
        run: yarn test:json
      - name: Report Coverage
        if: ${{ matrix.node-version == 14 }}
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage/coverage-final.json
          name: codecov